server:
  port: 8006
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
ribbon: 
  ReadTimeout: 60000    
  ConnectTimeout: 60000 
  maxAutoRetries: 0
feign:
  hystrix:
    enabled: true
hystrix:
  command: 
    default: 
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 5000
