spring:
  application:
    name: config  cloud:    config:      server:        git:          uri: https://github.com/ZacharyChao/config
          username: ZacharyChao
          password: 5917499627zlmm
eureka:  client:    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:  port: 8002