spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZacharyChao/config
          username: 
          password: 
server:
  port: 8000